using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace Reminder
{
    /// <summary>
    /// Interaction logic for EventsPresenterWindow.xaml
    /// </summary>
    public partial class EventsPresenterWindow : Window
    {
        public EventsPresenterWindow(EventsEntities events)
        {
            InitializeComponent();
            EventsData.ItemsSource = events.Events.ToList();
            EventsData.CanUserAddRows = false;
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            Close();
        }
        private void EventsData_AutoGeneratedColumns(object sender, EventArgs e)
        {
            EventsData.Columns[0].Header = "Event number";
            EventsData.Columns[1].Header = "Description";
            EventsData.Columns[2].Header = "Date";
            EventsData.Columns[3].Header = "Annually";
        }

        private void EventsData_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyType == typeof(System.DateTime))
                (e.Column as DataGridTextColumn).Binding.StringFormat = "dd/MM/yyyy";
        }
    }
}
